# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {runtcl-4}  -suppress 
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/VIVADO/decoderTest/decoderTest/decoderTest.cache/wt [current_project]
set_property parent.project_path D:/VIVADO/decoderTest/decoderTest/decoderTest.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths {
  d:/VIVADO/decoderTest/ip_repo/testDDR_1.0
  d:/VIVADO/decoderTest/ip_repo/myDDR_1.0
  d:/VIVADO/decoderTest/ip_repo
} [current_project]
update_ip_catalog
set_property ip_output_repo d:/VIVADO/decoderTest/decoderTest/decoderTest.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/hdl/decoderTest_wrapper.vhd
add_files D:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/decoderTest.bd
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_rst_s00_axi_aclk_100M_0/decoderTest_rst_s00_axi_aclk_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_rst_s00_axi_aclk_100M_0/decoderTest_rst_s00_axi_aclk_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_rst_s00_axi_aclk_100M_0/decoderTest_rst_s00_axi_aclk_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_axi_cdma_0_0/decoderTest_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_axi_cdma_0_0/decoderTest_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_1/bd_7988_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_1/bd_7988_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_2/bd_7988_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_3/bd_7988_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_4/bd_7988_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_5/bd_7988_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_6/bd_7988_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_7/bd_7988_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_8/bd_7988_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_9/bd_7988_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_10/bd_7988_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_11/bd_7988_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_12/bd_7988_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_13/bd_7988_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_14/bd_7988_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_15/bd_7988_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_16/bd_7988_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_20/bd_7988_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_21/bd_7988_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_22/bd_7988_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_23/bd_7988_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_24/bd_7988_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_25/bd_7988_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_26/bd_7988_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_27/bd_7988_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_28/bd_7988_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_29/bd_7988_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_30/bd_7988_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_31/bd_7988_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_33/bd_7988_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_34/bd_7988_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_35/bd_7988_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_36/bd_7988_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_37/bd_7988_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_38/bd_7988_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_40/bd_7988_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_41/bd_7988_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_42/bd_7988_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_43/bd_7988_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_44/bd_7988_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_smartconnect_0_0/bd_0/ip/ip_45/bd_7988_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_axi_bram_ctrl_0_0/decoderTest_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/ip/decoderTest_blk_mem_gen_0_0/decoderTest_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/VIVADO/decoderTest/decoderTest/decoderTest.srcs/sources_1/bd/decoderTest/decoderTest_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top decoderTest_wrapper -part xc7z020clg400-1 -directive RuntimeOptimized


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef decoderTest_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file decoderTest_wrapper_utilization_synth.rpt -pb decoderTest_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
