# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/decoderTest/decoderTest.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoderTest || ORIG_REF_NAME==decoderTest} -quiet] -quiet

# IP: bd/decoderTest/ip/decoderTest_decoder_0_0/decoderTest_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoderTest_decoder_0_0 || ORIG_REF_NAME==decoderTest_decoder_0_0} -quiet] -quiet

# IP: bd/decoderTest/ip/decoderTest_rst_s00_axi_aclk_100M_0/decoderTest_rst_s00_axi_aclk_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoderTest_rst_s00_axi_aclk_100M_0 || ORIG_REF_NAME==decoderTest_rst_s00_axi_aclk_100M_0} -quiet] -quiet

# IP: bd/decoderTest/ip/decoderTest_Instructions_0_0/decoderTest_Instructions_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoderTest_Instructions_0_0 || ORIG_REF_NAME==decoderTest_Instructions_0_0} -quiet] -quiet

# IP: bd/decoderTest/ip/decoderTest_axi_cdma_0_0/decoderTest_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoderTest_axi_cdma_0_0 || ORIG_REF_NAME==decoderTest_axi_cdma_0_0} -quiet] -quiet

# IP: bd/decoderTest/ip/decoderTest_smartconnect_0_0/decoderTest_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoderTest_smartconnect_0_0 || ORIG_REF_NAME==decoderTest_smartconnect_0_0} -quiet] -quiet

# IP: bd/decoderTest/ip/decoderTest_axi_bram_ctrl_0_0/decoderTest_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoderTest_axi_bram_ctrl_0_0 || ORIG_REF_NAME==decoderTest_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/decoderTest/ip/decoderTest_blk_mem_gen_0_0/decoderTest_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoderTest_blk_mem_gen_0_0 || ORIG_REF_NAME==decoderTest_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/decoderTest/decoderTest_ooc.xdc
